application:
  frontend:
    url: http://localhost:3000/
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: http://localhost:8080/oauth2/callback/google
  mail:
    host: smtp.gmail.com
    port: 587
    username: mishamakytonin@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: debug
server:
  port: 8080